let rowId = 0;
let tablerow = document.createElement(div);
tablerow.className="tablerow borderstyle";
tablerow.id = rowId;
let cardName = document.createElement(div);
cardName.className = "tablecontent borderstyle name";
let cardBaseType = document.createElement(div);
cardBaseType.className = "tablecontent borderstyle cardtype";
let cardAttribute = document.createElement(div);
cardAttribute.className = "tablecontent borderstyle atribute";
let cardLevel = document.createElement(div);
cardLevel.className = "tablecontent borderstyle level";
let cardScale = document.createElement(div);
cardScale.className = "tablecontent borderstyle pendulum";
let cardType = document.createElement(div);
cardType.className = "tablecontent borderstyle type";
let cardTuner = document.createElement(div);
cardTuner.className = "tablecontent borderstyle tuner";
let cardATK  = document.createElement(div);
cardATK.className = "tablecontent borderstyle atk";
let cardCount = document.createElement(div);
cardCount.className = "tablecontent borderstyle count";
let cardNotes = document.createElement(div);
cardNotes.className = "tablecontent borderstyle notes";
rowId++;

